# Generated by Django 4.2.3 on 2023-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The Neme Of The Movie.', max_length=100)),
                ('date', models.DateField(verbose_name='Date The Movie Was Released.')),
            ],
        ),
    ]
